---
title: Basicspace
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: kaitlyn@basic-space.com
description: A minimal, clean starting point using Jeykll + Tachyons
baseurl: ""
url: http://basic-space.com
name: Basicspace
permalink: pretty
port: 4040
markdown: kramdown
exclude:
- node_modules
